app = "wabotgemini"  # You can give your app any name

[build]
  image = "Dockerfile"

[env]
  # Set any environment variables here if needed
  # For example:
  # GITHUB_TOKEN = "your-github-token"

[[services]]
  internal_port = 8080
  protocol = "http"
  script = "npm start"
  ports = [{ port = "80", handlers = ["http"] }]
